name = "lean_adc"
version = "0.1.0"
defaultTargets = ["lean_adc"]

[[lean_lib]]
name = "lean_adc"
roots = ["extraction.lean_adc"]

[[require]]
name = "Hax"
path = "../../../../hax-lib/proof-libs/lean"
