name = "lean_chacha20"
version = "0.1.0"
defaultTargets = ["lean_chacha20"]

[[lean_lib]]
name = "lean_chacha20"
roots = ["extraction.lean_chacha20"]

[[require]]
name = "Hax"
path = "../../../../hax-lib/proof-libs/lean"
