name = "Core_models"
version = "0.1.0"
defaultTargets = ["Core_models"]

[[lean_lib]]
name = "Core_models"
roots = ["extraction.Core_models"]

[[require]]
name = "Hax"
path = "../../../../hax-lib/proof-libs/lean"
